left-and-right-margins:
  default: 100
  type: integer
  description:
    en: "Left and right margins"
    ja: "左右の余白"
sidebar_create-topic:
  default: false
  type: bool
  description:
    en: "Add a button to create a new topic in the sidebar"
    ja: "サイドバーに新規トピックを作成するボタンを追加する"
